export {
  bigQueryDialect,
  createSqlLanguageService,
  dremioDialect,
  duckdbDialect,
  postgresDialect,
} from "./session.js";
export type {
  OpenSqlDocument,
  SqlCatalogContext,
  SqlContextInput,
  SqlDialect,
  SqlDocumentChanges,
  SqlDocumentContext,
  SqlDocumentEdit,
  SqlEmbeddedRegion,
  SqlDocumentReplacement,
  SqlDocumentSession,
  SqlDocumentUpdate,
  SqlIdentifierComponent,
  SqlIdentifierPath,
  SqlLanguageService,
  SqlLanguageServiceOptions,
  SqlPlainData,
  SqlRevision,
  SqlSessionErrorCode,
  SqlTextChange,
  SqlTextRange,
} from "./types.js";
export { SqlSessionError } from "./types.js";
export type {
  SqlCanonicalRelationPath,
  SqlCatalogEpoch,
  SqlCatalogFailureCode,
  SqlCatalogProviderReport,
  SqlCatalogReadyCoverage,
  SqlCatalogRelation,
  SqlCatalogRelationKind,
  SqlCatalogRetryPolicy,
  SqlCatalogSearchRequest,
  SqlCatalogSearchResponse,
  SqlCompletionCancellationReason,
  SqlCompletionIssue,
  SqlCompletionRequest,
  SqlCompletionRefreshToken,
  SqlCompletionTrigger,
  SqlDisposable,
  SqlRelationCatalogProvider,
  SqlCompletionItem,
  SqlCompletionList,
  SqlCompletionResult,
  SqlCompletionTask,
  SqlSessionChangeEvent,
  SqlSessionChangeReason,
} from "./relation-completion-types.js";
