export {
  bigQueryDialect,
  createSqlLanguageService,
  dremioDialect,
  duckdbDialect,
  postgresDialect,
} from "./session.js";
export type {
  SqlColumnCatalogBatchRequest,
  SqlColumnCatalogBatchResponse,
  SqlColumnCatalogColumn,
  SqlColumnCatalogCoverage,
  SqlColumnCatalogProvider,
  SqlColumnCatalogProvenance,
  SqlColumnCatalogProviderRelationResult,
  SqlColumnCatalogProviderResponse,
  SqlColumnCatalogRelationReference,
  SqlColumnCatalogRelationResult,
  SqlColumnCatalogResolvedColumn,
} from "./column-catalog-types.js";
export type {
  SqlCanonicalNamespacePath,
  SqlNamespaceCatalogContainer,
  SqlNamespaceCatalogProvider,
  SqlNamespaceCatalogProviderResponse,
  SqlNamespaceCatalogProvenance,
  SqlNamespaceCatalogResolvedContainer,
  SqlNamespaceCatalogSearchRequest,
  SqlNamespaceCatalogSearchResponse,
  SqlNamespaceContainerRole,
  SqlNamespacePathComponent,
  SqlNamespaceQuerySite,
} from "./namespace-catalog-types.js";
export type {
  OpenSqlDocument,
  SqlCatalogContext,
  SqlContextInput,
  SqlDialect,
  SqlDocumentChanges,
  SqlDocumentContext,
  SqlDocumentEdit,
  SqlEmbeddedRegion,
  SqlDocumentReplacement,
  SqlDocumentSession,
  SqlDocumentUpdate,
  SqlIdentifierComponent,
  SqlIdentifierPath,
  SqlLanguageService,
  SqlLanguageServiceOptions,
  SqlPlainData,
  SqlRevision,
  SqlSessionErrorCode,
  SqlTextChange,
  SqlTextRange,
} from "./types.js";
export { SqlSessionError } from "./types.js";
export {
  MAX_SQL_FEATURE_RESULTS,
  MAX_SQL_FEATURE_TEXT_LENGTH,
} from "./language-features.js";
export type {
  SqlCodeAction,
  SqlDiagnostic,
  SqlDiagnosticSeverity,
  SqlDiagnosticsRequest,
  SqlDocumentEditResult,
  SqlDocumentSymbol,
  SqlDocumentSymbolKind,
  SqlFeatureCancelled,
  SqlFeatureDocument,
  SqlFeatureProviderReport,
  SqlFeatureProviderRequest,
  SqlFeatureReady,
  SqlFeatureResult,
  SqlFeatureTask,
  SqlFeatureUnavailable,
  SqlFoldingRange,
  SqlFormatRequest,
  SqlHover,
  SqlLanguageFeatureMethods,
  SqlLanguageFeatureProvider,
  SqlLocation,
  SqlMarkupContent,
  SqlPositionFeatureRequest,
  SqlRangeFeatureRequest,
  SqlRenameRequest,
} from "./language-features.js";
export type {
  SqlExactStatementBoundary,
  SqlOpaqueStatementBoundary,
  SqlStatementAffinity,
  SqlStatementBoundariesIntersectingRequest,
  SqlStatementBoundariesIntersectingResult,
  SqlStatementBoundary,
  SqlStatementBoundaryAtRequest,
  SqlStatementBoundaryAtResult,
  SqlStatementLexicalEnd,
  SqlStatementOpaqueReason,
  SqlStatementUnterminatedConstruct,
} from "./statement-boundary-types.js";
export type {
  SqlCanonicalRelationPath,
  SqlCatalogCompletionProvenance,
  SqlCatalogContainerComponent,
  SqlCatalogContainerRole,
  SqlCatalogEpoch,
  SqlCatalogFailureCode,
  SqlCatalogInvalidation,
  SqlCatalogMatchQuality,
  SqlCatalogProviderReport,
  SqlCatalogProviderUnavailableReason,
  SqlCatalogReadyCoverage,
  SqlCatalogRelation,
  SqlCatalogRelationComponent,
  SqlCatalogRelationKind,
  SqlCatalogRetryPolicy,
  SqlCatalogSearchRequest,
  SqlCatalogSearchResponse,
  SqlCatalogSubscriptionCleanup,
  SqlCompletionCancellationReason,
  SqlCompletionUnavailableReason,
  SqlCteCompletionProvenance,
  SqlColumnCatalogProviderReport,
  SqlColumnCatalogFailure,
  SqlColumnCompletionProvenance,
  SqlQueryOutputCompletionProvenance,
  SqlQueryOutputProviderReport,
  SqlCompletionProviderReport,
  SqlCompletionIssue,
  SqlCompletionRequest,
  SqlCompletionRefreshToken,
  SqlNamespaceCatalogProviderReport,
  SqlNamespaceCompletionProvenance,
  SqlCompletionTrigger,
  SqlDisposable,
  SqlRelationCatalogProvider,
  SqlCompletionItem,
  SqlCompletionList,
  SqlCompletionResult,
  SqlCompletionTask,
  SqlSessionChangeEvent,
  SqlSessionChangeReason,
  SqlServiceFailure,
} from "./relation-completion-types.js";
